"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.any_pb2
import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.struct_pb2
import google.protobuf.timestamp_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class Record(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VERSION_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    MODIFIED_AT_FIELD_NUMBER: builtins.int
    DELETED_AT_FIELD_NUMBER: builtins.int
    version: builtins.int
    type: builtins.str
    id: builtins.str
    @property
    def data(self) -> google.protobuf.any_pb2.Any: ...
    @property
    def modified_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def deleted_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        version: builtins.int = ...,
        type: builtins.str = ...,
        id: builtins.str = ...,
        data: google.protobuf.any_pb2.Any | None = ...,
        modified_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        deleted_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["data", b"data", "deleted_at", b"deleted_at", "modified_at", b"modified_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["data", b"data", "deleted_at", b"deleted_at", "id", b"id", "modified_at", b"modified_at", "type", b"type", "version", b"version"]) -> None: ...

global___Record = Record

class Versions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERVER_VERSION_FIELD_NUMBER: builtins.int
    LATEST_RECORD_VERSION_FIELD_NUMBER: builtins.int
    server_version: builtins.int
    """the server version indicates the version of the server storing the data"""
    latest_record_version: builtins.int
    def __init__(
        self,
        *,
        server_version: builtins.int = ...,
        latest_record_version: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["latest_record_version", b"latest_record_version", "server_version", b"server_version"]) -> None: ...

global___Versions = Versions

class Options(google.protobuf.message.Message):
    """Options are the options for a type stored in the databroker."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CAPACITY_FIELD_NUMBER: builtins.int
    capacity: builtins.int
    """capacity sets a maximum size for the given type. Once the capacity is
    reached the oldest records will be removed.
    """
    def __init__(
        self,
        *,
        capacity: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_capacity", b"_capacity", "capacity", b"capacity"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_capacity", b"_capacity", "capacity", b"capacity"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_capacity", b"_capacity"]) -> typing_extensions.Literal["capacity"] | None: ...

global___Options = Options

class GetRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    type: builtins.str
    id: builtins.str
    def __init__(
        self,
        *,
        type: builtins.str = ...,
        id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id", "type", b"type"]) -> None: ...

global___GetRequest = GetRequest

class GetResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RECORD_FIELD_NUMBER: builtins.int
    @property
    def record(self) -> global___Record: ...
    def __init__(
        self,
        *,
        record: global___Record | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["record", b"record"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["record", b"record"]) -> None: ...

global___GetResponse = GetResponse

class QueryRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    QUERY_FIELD_NUMBER: builtins.int
    OFFSET_FIELD_NUMBER: builtins.int
    LIMIT_FIELD_NUMBER: builtins.int
    FILTER_FIELD_NUMBER: builtins.int
    type: builtins.str
    query: builtins.str
    offset: builtins.int
    limit: builtins.int
    @property
    def filter(self) -> google.protobuf.struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        type: builtins.str = ...,
        query: builtins.str = ...,
        offset: builtins.int = ...,
        limit: builtins.int = ...,
        filter: google.protobuf.struct_pb2.Struct | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["filter", b"filter"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["filter", b"filter", "limit", b"limit", "offset", b"offset", "query", b"query", "type", b"type"]) -> None: ...

global___QueryRequest = QueryRequest

class QueryResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RECORDS_FIELD_NUMBER: builtins.int
    TOTAL_COUNT_FIELD_NUMBER: builtins.int
    SERVER_VERSION_FIELD_NUMBER: builtins.int
    RECORD_VERSION_FIELD_NUMBER: builtins.int
    @property
    def records(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Record]: ...
    total_count: builtins.int
    server_version: builtins.int
    record_version: builtins.int
    def __init__(
        self,
        *,
        records: collections.abc.Iterable[global___Record] | None = ...,
        total_count: builtins.int = ...,
        server_version: builtins.int = ...,
        record_version: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["record_version", b"record_version", "records", b"records", "server_version", b"server_version", "total_count", b"total_count"]) -> None: ...

global___QueryResponse = QueryResponse

class PutRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RECORDS_FIELD_NUMBER: builtins.int
    @property
    def records(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Record]: ...
    def __init__(
        self,
        *,
        records: collections.abc.Iterable[global___Record] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["records", b"records"]) -> None: ...

global___PutRequest = PutRequest

class PutResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERVER_VERSION_FIELD_NUMBER: builtins.int
    RECORDS_FIELD_NUMBER: builtins.int
    server_version: builtins.int
    @property
    def records(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Record]: ...
    def __init__(
        self,
        *,
        server_version: builtins.int = ...,
        records: collections.abc.Iterable[global___Record] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["records", b"records", "server_version", b"server_version"]) -> None: ...

global___PutResponse = PutResponse

class SetOptionsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    OPTIONS_FIELD_NUMBER: builtins.int
    type: builtins.str
    @property
    def options(self) -> global___Options: ...
    def __init__(
        self,
        *,
        type: builtins.str = ...,
        options: global___Options | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["options", b"options"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["options", b"options", "type", b"type"]) -> None: ...

global___SetOptionsRequest = SetOptionsRequest

class SetOptionsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OPTIONS_FIELD_NUMBER: builtins.int
    @property
    def options(self) -> global___Options: ...
    def __init__(
        self,
        *,
        options: global___Options | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["options", b"options"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["options", b"options"]) -> None: ...

global___SetOptionsResponse = SetOptionsResponse

class SyncRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERVER_VERSION_FIELD_NUMBER: builtins.int
    RECORD_VERSION_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    server_version: builtins.int
    record_version: builtins.int
    type: builtins.str
    def __init__(
        self,
        *,
        server_version: builtins.int = ...,
        record_version: builtins.int = ...,
        type: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["record_version", b"record_version", "server_version", b"server_version", "type", b"type"]) -> None: ...

global___SyncRequest = SyncRequest

class SyncResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RECORD_FIELD_NUMBER: builtins.int
    @property
    def record(self) -> global___Record: ...
    def __init__(
        self,
        *,
        record: global___Record | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["record", b"record"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["record", b"record"]) -> None: ...

global___SyncResponse = SyncResponse

class SyncLatestRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    type: builtins.str
    def __init__(
        self,
        *,
        type: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["type", b"type"]) -> None: ...

global___SyncLatestRequest = SyncLatestRequest

class SyncLatestResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RECORD_FIELD_NUMBER: builtins.int
    VERSIONS_FIELD_NUMBER: builtins.int
    @property
    def record(self) -> global___Record: ...
    @property
    def versions(self) -> global___Versions: ...
    def __init__(
        self,
        *,
        record: global___Record | None = ...,
        versions: global___Versions | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["record", b"record", "response", b"response", "versions", b"versions"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["record", b"record", "response", b"response", "versions", b"versions"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["response", b"response"]) -> typing_extensions.Literal["record", "versions"] | None: ...

global___SyncLatestResponse = SyncLatestResponse

class AcquireLeaseRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    DURATION_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Name is the name of the lease. Only a single client can hold the lease on
    the specified name at any one time.
    """
    @property
    def duration(self) -> google.protobuf.duration_pb2.Duration:
        """Duration is the duration of the lease. After the duration is reached the
        lease can be acquired by other clients.
        """
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        duration: google.protobuf.duration_pb2.Duration | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["duration", b"duration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["duration", b"duration", "name", b"name"]) -> None: ...

global___AcquireLeaseRequest = AcquireLeaseRequest

class AcquireLeaseResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.str
    """Id is the id of the acquired lease. Subsequent calls to release or renew
    will need both the lease name and the lease id.
    """
    def __init__(
        self,
        *,
        id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id"]) -> None: ...

global___AcquireLeaseResponse = AcquireLeaseResponse

class ReleaseLeaseRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    name: builtins.str
    id: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id", "name", b"name"]) -> None: ...

global___ReleaseLeaseRequest = ReleaseLeaseRequest

class RenewLeaseRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    DURATION_FIELD_NUMBER: builtins.int
    name: builtins.str
    id: builtins.str
    @property
    def duration(self) -> google.protobuf.duration_pb2.Duration: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        id: builtins.str = ...,
        duration: google.protobuf.duration_pb2.Duration | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["duration", b"duration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["duration", b"duration", "id", b"id", "name", b"name"]) -> None: ...

global___RenewLeaseRequest = RenewLeaseRequest
