# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/pomerium/pomerium/pkg/grpc/identity/identity.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=github.com/pomerium/pomerium/pkg/grpc/identity/identity.proto\x12\x11pomerium.identity\"\x82\x02\n\x08Provider\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tclient_id\x18\x02 \x01(\t\x12\x15\n\rclient_secret\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\t\x12\x0e\n\x06scopes\x18\x05 \x03(\t\x12\x17\n\x0fservice_account\x18\x06 \x01(\t\x12\x0b\n\x03url\x18\x07 \x01(\t\x12\x46\n\x0erequest_params\x18\x08 \x03(\x0b\x32..pomerium.identity.Provider.RequestParamsEntry\x1a\x34\n\x12RequestParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x30Z.github.com/pomerium/pomerium/pkg/grpc/identityb\x06proto3')



_PROVIDER = DESCRIPTOR.message_types_by_name['Provider']
_PROVIDER_REQUESTPARAMSENTRY = _PROVIDER.nested_types_by_name['RequestParamsEntry']
Provider = _reflection.GeneratedProtocolMessageType('Provider', (_message.Message,), {

  'RequestParamsEntry' : _reflection.GeneratedProtocolMessageType('RequestParamsEntry', (_message.Message,), {
    'DESCRIPTOR' : _PROVIDER_REQUESTPARAMSENTRY,
    '__module__' : 'github.com.pomerium.pomerium.pkg.grpc.identity.identity_pb2'
    # @@protoc_insertion_point(class_scope:pomerium.identity.Provider.RequestParamsEntry)
    })
  ,
  'DESCRIPTOR' : _PROVIDER,
  '__module__' : 'github.com.pomerium.pomerium.pkg.grpc.identity.identity_pb2'
  # @@protoc_insertion_point(class_scope:pomerium.identity.Provider)
  })
_sym_db.RegisterMessage(Provider)
_sym_db.RegisterMessage(Provider.RequestParamsEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z.github.com/pomerium/pomerium/pkg/grpc/identity'
  _PROVIDER_REQUESTPARAMSENTRY._options = None
  _PROVIDER_REQUESTPARAMSENTRY._serialized_options = b'8\001'
  _PROVIDER._serialized_start=85
  _PROVIDER._serialized_end=343
  _PROVIDER_REQUESTPARAMSENTRY._serialized_start=291
  _PROVIDER_REQUESTPARAMSENTRY._serialized_end=343
# @@protoc_insertion_point(module_scope)
