"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.descriptor_pb2
import google.protobuf.internal.extension_dict
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class VersioningAnnotation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PREVIOUS_MESSAGE_TYPE_FIELD_NUMBER: builtins.int
    previous_message_type: builtins.str
    """Track the previous message type. E.g. this message might be
    udpa.foo.v3alpha.Foo and it was previously udpa.bar.v2.Bar. This
    information is consumed by UDPA via proto descriptors.
    """
    def __init__(
        self,
        *,
        previous_message_type: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["previous_message_type", b"previous_message_type"]) -> None: ...

global___VersioningAnnotation = VersioningAnnotation

VERSIONING_FIELD_NUMBER: builtins.int
versioning: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[google.protobuf.descriptor_pb2.MessageOptions, global___VersioningAnnotation]
"""Magic number derived from 0x78 ('x') 0x44 ('D') 0x53 ('S')"""
