"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class WebAuthnOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _AttestationConveyancePreference:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _AttestationConveyancePreferenceEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[WebAuthnOptions._AttestationConveyancePreference.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        NONE: WebAuthnOptions._AttestationConveyancePreference.ValueType  # 0
        INDIRECT: WebAuthnOptions._AttestationConveyancePreference.ValueType  # 1
        DIRECT: WebAuthnOptions._AttestationConveyancePreference.ValueType  # 2
        ENTERPRISE: WebAuthnOptions._AttestationConveyancePreference.ValueType  # 3

    class AttestationConveyancePreference(_AttestationConveyancePreference, metaclass=_AttestationConveyancePreferenceEnumTypeWrapper): ...
    NONE: WebAuthnOptions.AttestationConveyancePreference.ValueType  # 0
    INDIRECT: WebAuthnOptions.AttestationConveyancePreference.ValueType  # 1
    DIRECT: WebAuthnOptions.AttestationConveyancePreference.ValueType  # 2
    ENTERPRISE: WebAuthnOptions.AttestationConveyancePreference.ValueType  # 3

    class _AuthenticatorAttachment:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _AuthenticatorAttachmentEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[WebAuthnOptions._AuthenticatorAttachment.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        PLATFORM: WebAuthnOptions._AuthenticatorAttachment.ValueType  # 0
        CROSS_PLATFORM: WebAuthnOptions._AuthenticatorAttachment.ValueType  # 2

    class AuthenticatorAttachment(_AuthenticatorAttachment, metaclass=_AuthenticatorAttachmentEnumTypeWrapper): ...
    PLATFORM: WebAuthnOptions.AuthenticatorAttachment.ValueType  # 0
    CROSS_PLATFORM: WebAuthnOptions.AuthenticatorAttachment.ValueType  # 2

    class _PublicKeyCredentialType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _PublicKeyCredentialTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[WebAuthnOptions._PublicKeyCredentialType.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        PUBLIC_KEY: WebAuthnOptions._PublicKeyCredentialType.ValueType  # 0

    class PublicKeyCredentialType(_PublicKeyCredentialType, metaclass=_PublicKeyCredentialTypeEnumTypeWrapper): ...
    PUBLIC_KEY: WebAuthnOptions.PublicKeyCredentialType.ValueType  # 0

    class _ResidentKeyRequirement:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ResidentKeyRequirementEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[WebAuthnOptions._ResidentKeyRequirement.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        RESIDENT_KEY_DISCOURAGED: WebAuthnOptions._ResidentKeyRequirement.ValueType  # 0
        RESIDENT_KEY_PREFERRED: WebAuthnOptions._ResidentKeyRequirement.ValueType  # 1
        RESIDENT_KEY_REQUIRED: WebAuthnOptions._ResidentKeyRequirement.ValueType  # 2

    class ResidentKeyRequirement(_ResidentKeyRequirement, metaclass=_ResidentKeyRequirementEnumTypeWrapper): ...
    RESIDENT_KEY_DISCOURAGED: WebAuthnOptions.ResidentKeyRequirement.ValueType  # 0
    RESIDENT_KEY_PREFERRED: WebAuthnOptions.ResidentKeyRequirement.ValueType  # 1
    RESIDENT_KEY_REQUIRED: WebAuthnOptions.ResidentKeyRequirement.ValueType  # 2

    class _UserVerificationRequirement:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _UserVerificationRequirementEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[WebAuthnOptions._UserVerificationRequirement.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        USER_VERIFICATION_DISCOURAGED: WebAuthnOptions._UserVerificationRequirement.ValueType  # 0
        USER_VERIFICATION_PREFERRED: WebAuthnOptions._UserVerificationRequirement.ValueType  # 1
        USER_VERIFICATION_REQUIRED: WebAuthnOptions._UserVerificationRequirement.ValueType  # 2

    class UserVerificationRequirement(_UserVerificationRequirement, metaclass=_UserVerificationRequirementEnumTypeWrapper): ...
    USER_VERIFICATION_DISCOURAGED: WebAuthnOptions.UserVerificationRequirement.ValueType  # 0
    USER_VERIFICATION_PREFERRED: WebAuthnOptions.UserVerificationRequirement.ValueType  # 1
    USER_VERIFICATION_REQUIRED: WebAuthnOptions.UserVerificationRequirement.ValueType  # 2

    class AuthenticatorSelectionCriteria(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        AUTHENTICATOR_ATTACHMENT_FIELD_NUMBER: builtins.int
        REQUIRE_RESIDENT_KEY_FIELD_NUMBER: builtins.int
        RESIDENT_KEY_REQUIREMENT_FIELD_NUMBER: builtins.int
        USER_VERIFICATION_FIELD_NUMBER: builtins.int
        authenticator_attachment: global___WebAuthnOptions.AuthenticatorAttachment.ValueType
        require_resident_key: builtins.bool
        resident_key_requirement: global___WebAuthnOptions.ResidentKeyRequirement.ValueType
        user_verification: global___WebAuthnOptions.UserVerificationRequirement.ValueType
        def __init__(
            self,
            *,
            authenticator_attachment: global___WebAuthnOptions.AuthenticatorAttachment.ValueType | None = ...,
            require_resident_key: builtins.bool | None = ...,
            resident_key_requirement: global___WebAuthnOptions.ResidentKeyRequirement.ValueType | None = ...,
            user_verification: global___WebAuthnOptions.UserVerificationRequirement.ValueType | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["_authenticator_attachment", b"_authenticator_attachment", "_require_resident_key", b"_require_resident_key", "_resident_key_requirement", b"_resident_key_requirement", "_user_verification", b"_user_verification", "authenticator_attachment", b"authenticator_attachment", "require_resident_key", b"require_resident_key", "resident_key_requirement", b"resident_key_requirement", "user_verification", b"user_verification"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["_authenticator_attachment", b"_authenticator_attachment", "_require_resident_key", b"_require_resident_key", "_resident_key_requirement", b"_resident_key_requirement", "_user_verification", b"_user_verification", "authenticator_attachment", b"authenticator_attachment", "require_resident_key", b"require_resident_key", "resident_key_requirement", b"resident_key_requirement", "user_verification", b"user_verification"]) -> None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing_extensions.Literal["_authenticator_attachment", b"_authenticator_attachment"]) -> typing_extensions.Literal["authenticator_attachment"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing_extensions.Literal["_require_resident_key", b"_require_resident_key"]) -> typing_extensions.Literal["require_resident_key"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing_extensions.Literal["_resident_key_requirement", b"_resident_key_requirement"]) -> typing_extensions.Literal["resident_key_requirement"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing_extensions.Literal["_user_verification", b"_user_verification"]) -> typing_extensions.Literal["user_verification"] | None: ...

    class PublicKeyCredentialParameters(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ALG_FIELD_NUMBER: builtins.int
        TYPE_FIELD_NUMBER: builtins.int
        alg: builtins.int
        type: global___WebAuthnOptions.PublicKeyCredentialType.ValueType
        def __init__(
            self,
            *,
            alg: builtins.int = ...,
            type: global___WebAuthnOptions.PublicKeyCredentialType.ValueType = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["alg", b"alg", "type", b"type"]) -> None: ...

    ATTESTATION_FIELD_NUMBER: builtins.int
    AUTHENTICATOR_SELECTION_FIELD_NUMBER: builtins.int
    PUB_KEY_CRED_PARAMS_FIELD_NUMBER: builtins.int
    attestation: global___WebAuthnOptions.AttestationConveyancePreference.ValueType
    @property
    def authenticator_selection(self) -> global___WebAuthnOptions.AuthenticatorSelectionCriteria: ...
    @property
    def pub_key_cred_params(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___WebAuthnOptions.PublicKeyCredentialParameters]: ...
    def __init__(
        self,
        *,
        attestation: global___WebAuthnOptions.AttestationConveyancePreference.ValueType | None = ...,
        authenticator_selection: global___WebAuthnOptions.AuthenticatorSelectionCriteria | None = ...,
        pub_key_cred_params: collections.abc.Iterable[global___WebAuthnOptions.PublicKeyCredentialParameters] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_attestation", b"_attestation", "_authenticator_selection", b"_authenticator_selection", "attestation", b"attestation", "authenticator_selection", b"authenticator_selection"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_attestation", b"_attestation", "_authenticator_selection", b"_authenticator_selection", "attestation", b"attestation", "authenticator_selection", b"authenticator_selection", "pub_key_cred_params", b"pub_key_cred_params"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_attestation", b"_attestation"]) -> typing_extensions.Literal["attestation"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_authenticator_selection", b"_authenticator_selection"]) -> typing_extensions.Literal["authenticator_selection"] | None: ...

global___WebAuthnOptions = WebAuthnOptions

class Type(google.protobuf.message.Message):
    """A Type constrains which kinds of devices are allowed to be registered."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class WebAuthn(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        OPTIONS_FIELD_NUMBER: builtins.int
        @property
        def options(self) -> global___WebAuthnOptions: ...
        def __init__(
            self,
            *,
            options: global___WebAuthnOptions | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["options", b"options"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["options", b"options"]) -> None: ...

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    WEBAUTHN_FIELD_NUMBER: builtins.int
    id: builtins.str
    name: builtins.str
    @property
    def webauthn(self) -> global___Type.WebAuthn: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        name: builtins.str = ...,
        webauthn: global___Type.WebAuthn | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["specifier", b"specifier", "webauthn", b"webauthn"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id", "name", b"name", "specifier", b"specifier", "webauthn", b"webauthn"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["specifier", b"specifier"]) -> typing_extensions.Literal["webauthn"] | None: ...

global___Type = Type

class Enrollment(google.protobuf.message.Message):
    """An Enrollment is used to approve a user's device."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    TYPE_ID_FIELD_NUMBER: builtins.int
    CREDENTIAL_ID_FIELD_NUMBER: builtins.int
    USER_ID_FIELD_NUMBER: builtins.int
    APPROVED_BY_FIELD_NUMBER: builtins.int
    ENROLLED_AT_FIELD_NUMBER: builtins.int
    USER_AGENT_FIELD_NUMBER: builtins.int
    IP_ADDRESS_FIELD_NUMBER: builtins.int
    id: builtins.str
    type_id: builtins.str
    credential_id: builtins.str
    user_id: builtins.str
    approved_by: builtins.str
    @property
    def enrolled_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    user_agent: builtins.str
    ip_address: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        type_id: builtins.str = ...,
        credential_id: builtins.str = ...,
        user_id: builtins.str = ...,
        approved_by: builtins.str = ...,
        enrolled_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        user_agent: builtins.str = ...,
        ip_address: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["enrolled_at", b"enrolled_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["approved_by", b"approved_by", "credential_id", b"credential_id", "enrolled_at", b"enrolled_at", "id", b"id", "ip_address", b"ip_address", "type_id", b"type_id", "user_agent", b"user_agent", "user_id", b"user_id"]) -> None: ...

global___Enrollment = Enrollment

class Credential(google.protobuf.message.Message):
    """A Credential is a user's device-specific credential."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class WebAuthn(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ID_FIELD_NUMBER: builtins.int
        PUBLIC_KEY_FIELD_NUMBER: builtins.int
        REGISTER_OPTIONS_FIELD_NUMBER: builtins.int
        REGISTER_RESPONSE_FIELD_NUMBER: builtins.int
        AUTHENTICATE_RESPONSE_FIELD_NUMBER: builtins.int
        id: builtins.bytes
        public_key: builtins.bytes
        register_options: builtins.bytes
        """the options that were used to do initial registration"""
        register_response: builtins.bytes
        """the response returned from initial registration"""
        @property
        def authenticate_response(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]:
            """subsequent authenticate responses"""
        def __init__(
            self,
            *,
            id: builtins.bytes = ...,
            public_key: builtins.bytes = ...,
            register_options: builtins.bytes = ...,
            register_response: builtins.bytes = ...,
            authenticate_response: collections.abc.Iterable[builtins.bytes] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["authenticate_response", b"authenticate_response", "id", b"id", "public_key", b"public_key", "register_options", b"register_options", "register_response", b"register_response"]) -> None: ...

    ID_FIELD_NUMBER: builtins.int
    TYPE_ID_FIELD_NUMBER: builtins.int
    ENROLLMENT_ID_FIELD_NUMBER: builtins.int
    USER_ID_FIELD_NUMBER: builtins.int
    WEBAUTHN_FIELD_NUMBER: builtins.int
    id: builtins.str
    type_id: builtins.str
    enrollment_id: builtins.str
    user_id: builtins.str
    @property
    def webauthn(self) -> global___Credential.WebAuthn: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        type_id: builtins.str = ...,
        enrollment_id: builtins.str = ...,
        user_id: builtins.str = ...,
        webauthn: global___Credential.WebAuthn | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["specifier", b"specifier", "webauthn", b"webauthn"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["enrollment_id", b"enrollment_id", "id", b"id", "specifier", b"specifier", "type_id", b"type_id", "user_id", b"user_id", "webauthn", b"webauthn"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["specifier", b"specifier"]) -> typing_extensions.Literal["webauthn"] | None: ...

global___Credential = Credential

class OwnerCredentialRecord(google.protobuf.message.Message):
    """An OwnerCredentialRecord is used to track credential owners to prevent credential re-use."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    OWNER_ID_FIELD_NUMBER: builtins.int
    PUBLIC_KEY_FIELD_NUMBER: builtins.int
    id: builtins.bytes
    owner_id: builtins.bytes
    public_key: builtins.bytes
    def __init__(
        self,
        *,
        id: builtins.bytes = ...,
        owner_id: builtins.bytes = ...,
        public_key: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id", "owner_id", b"owner_id", "public_key", b"public_key"]) -> None: ...

global___OwnerCredentialRecord = OwnerCredentialRecord
