# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: audit/audit.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from envoy.service.auth.v3 import external_auth_pb2 as envoy_dot_service_dot_auth_dot_v3_dot_external__auth__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61udit/audit.proto\x12\x0epomerium.audit\x1a)envoy/service/auth/v3/external_auth.proto\"v\n\x06Record\x12\x34\n\x07request\x18\x01 \x01(\x0b\x32#.envoy.service.auth.v3.CheckRequest\x12\x36\n\x08response\x18\x02 \x01(\x0b\x32$.envoy.service.auth.v3.CheckResponseB-Z+github.com/pomerium/pomerium/pkg/grpc/auditb\x06proto3')



_RECORD = DESCRIPTOR.message_types_by_name['Record']
Record = _reflection.GeneratedProtocolMessageType('Record', (_message.Message,), {
  'DESCRIPTOR' : _RECORD,
  '__module__' : 'audit.audit_pb2'
  # @@protoc_insertion_point(class_scope:pomerium.audit.Record)
  })
_sym_db.RegisterMessage(Record)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z+github.com/pomerium/pomerium/pkg/grpc/audit'
  _RECORD._serialized_start=80
  _RECORD._serialized_end=198
# @@protoc_insertion_point(module_scope)
