"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import envoy.service.auth.v3.external_auth_pb2
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class Record(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REQUEST_FIELD_NUMBER: builtins.int
    RESPONSE_FIELD_NUMBER: builtins.int
    @property
    def request(self) -> envoy.service.auth.v3.external_auth_pb2.CheckRequest: ...
    @property
    def response(self) -> envoy.service.auth.v3.external_auth_pb2.CheckResponse: ...
    def __init__(
        self,
        *,
        request: envoy.service.auth.v3.external_auth_pb2.CheckRequest | None = ...,
        response: envoy.service.auth.v3.external_auth_pb2.CheckResponse | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["request", b"request", "response", b"response"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["request", b"request", "response", b"response"]) -> None: ...

global___Record = Record
