# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/pomerium/pomerium/pkg/grpc/session/session.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;github.com/pomerium/pomerium/pkg/grpc/session/session.proto\x12\x07session\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x96\x01\n\x07IDToken\x12\x0e\n\x06issuer\x18\x01 \x01(\t\x12\x0f\n\x07subject\x18\x02 \x01(\t\x12.\n\nexpires_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12-\n\tissued_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0b\n\x03raw\x18\x05 \x01(\t\"}\n\nOAuthToken\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x12\n\ntoken_type\x18\x02 \x01(\t\x12.\n\nexpires_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x15\n\rrefresh_token\x18\x04 \x01(\t\"\x8f\x05\n\x07Session\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12=\n\x12\x64\x65vice_credentials\x18\x11 \x03(\x0b\x32!.session.Session.DeviceCredential\x12-\n\tissued_at\x18\x0e \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nexpires_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\x0b\x61\x63\x63\x65ssed_at\x18\x12 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\"\n\x08id_token\x18\x06 \x01(\x0b\x32\x10.session.IDToken\x12(\n\x0boauth_token\x18\x07 \x01(\x0b\x32\x13.session.OAuthToken\x12,\n\x06\x63laims\x18\t \x03(\x0b\x32\x1c.session.Session.ClaimsEntry\x12\x10\n\x08\x61udience\x18\n \x03(\t\x12#\n\x16impersonate_session_id\x18\x0f \x01(\tH\x00\x88\x01\x01\x1an\n\x10\x44\x65viceCredential\x12\x0f\n\x07type_id\x18\x01 \x01(\t\x12-\n\x0bunavailable\x18\x02 \x01(\x0b\x32\x16.google.protobuf.EmptyH\x00\x12\x0c\n\x02id\x18\x03 \x01(\tH\x00\x42\x0c\n\ncredential\x1aI\n\x0b\x43laimsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.ListValue:\x02\x38\x01\x42\x19\n\x17_impersonate_session_idB/Z-github.com/pomerium/pomerium/pkg/grpc/sessionb\x06proto3')



_IDTOKEN = DESCRIPTOR.message_types_by_name['IDToken']
_OAUTHTOKEN = DESCRIPTOR.message_types_by_name['OAuthToken']
_SESSION = DESCRIPTOR.message_types_by_name['Session']
_SESSION_DEVICECREDENTIAL = _SESSION.nested_types_by_name['DeviceCredential']
_SESSION_CLAIMSENTRY = _SESSION.nested_types_by_name['ClaimsEntry']
IDToken = _reflection.GeneratedProtocolMessageType('IDToken', (_message.Message,), {
  'DESCRIPTOR' : _IDTOKEN,
  '__module__' : 'github.com.pomerium.pomerium.pkg.grpc.session.session_pb2'
  # @@protoc_insertion_point(class_scope:session.IDToken)
  })
_sym_db.RegisterMessage(IDToken)

OAuthToken = _reflection.GeneratedProtocolMessageType('OAuthToken', (_message.Message,), {
  'DESCRIPTOR' : _OAUTHTOKEN,
  '__module__' : 'github.com.pomerium.pomerium.pkg.grpc.session.session_pb2'
  # @@protoc_insertion_point(class_scope:session.OAuthToken)
  })
_sym_db.RegisterMessage(OAuthToken)

Session = _reflection.GeneratedProtocolMessageType('Session', (_message.Message,), {

  'DeviceCredential' : _reflection.GeneratedProtocolMessageType('DeviceCredential', (_message.Message,), {
    'DESCRIPTOR' : _SESSION_DEVICECREDENTIAL,
    '__module__' : 'github.com.pomerium.pomerium.pkg.grpc.session.session_pb2'
    # @@protoc_insertion_point(class_scope:session.Session.DeviceCredential)
    })
  ,

  'ClaimsEntry' : _reflection.GeneratedProtocolMessageType('ClaimsEntry', (_message.Message,), {
    'DESCRIPTOR' : _SESSION_CLAIMSENTRY,
    '__module__' : 'github.com.pomerium.pomerium.pkg.grpc.session.session_pb2'
    # @@protoc_insertion_point(class_scope:session.Session.ClaimsEntry)
    })
  ,
  'DESCRIPTOR' : _SESSION,
  '__module__' : 'github.com.pomerium.pomerium.pkg.grpc.session.session_pb2'
  # @@protoc_insertion_point(class_scope:session.Session)
  })
_sym_db.RegisterMessage(Session)
_sym_db.RegisterMessage(Session.DeviceCredential)
_sym_db.RegisterMessage(Session.ClaimsEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z-github.com/pomerium/pomerium/pkg/grpc/session'
  _SESSION_CLAIMSENTRY._options = None
  _SESSION_CLAIMSENTRY._serialized_options = b'8\001'
  _IDTOKEN._serialized_start=165
  _IDTOKEN._serialized_end=315
  _OAUTHTOKEN._serialized_start=317
  _OAUTHTOKEN._serialized_end=442
  _SESSION._serialized_start=445
  _SESSION._serialized_end=1100
  _SESSION_DEVICECREDENTIAL._serialized_start=888
  _SESSION_DEVICECREDENTIAL._serialized_end=998
  _SESSION_CLAIMSENTRY._serialized_start=1000
  _SESSION_CLAIMSENTRY._serialized_end=1073
# @@protoc_insertion_point(module_scope)
