# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crypt/crypt.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63rypt/crypt.proto\x12\x0epomerium.crypt\"m\n\rSealedMessage\x12\x0e\n\x06key_id\x18\x01 \x01(\t\x12\x1b\n\x13\x64\x61ta_encryption_key\x18\x02 \x01(\x0c\x12\x14\n\x0cmessage_type\x18\x03 \x01(\t\x12\x19\n\x11\x65ncrypted_message\x18\x04 \x01(\x0c\"2\n\x16PublicKeyEncryptionKey\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x42-Z+github.com/pomerium/pomerium/pkg/grpc/cryptb\x06proto3')



_SEALEDMESSAGE = DESCRIPTOR.message_types_by_name['SealedMessage']
_PUBLICKEYENCRYPTIONKEY = DESCRIPTOR.message_types_by_name['PublicKeyEncryptionKey']
SealedMessage = _reflection.GeneratedProtocolMessageType('SealedMessage', (_message.Message,), {
  'DESCRIPTOR' : _SEALEDMESSAGE,
  '__module__' : 'crypt.crypt_pb2'
  # @@protoc_insertion_point(class_scope:pomerium.crypt.SealedMessage)
  })
_sym_db.RegisterMessage(SealedMessage)

PublicKeyEncryptionKey = _reflection.GeneratedProtocolMessageType('PublicKeyEncryptionKey', (_message.Message,), {
  'DESCRIPTOR' : _PUBLICKEYENCRYPTIONKEY,
  '__module__' : 'crypt.crypt_pb2'
  # @@protoc_insertion_point(class_scope:pomerium.crypt.PublicKeyEncryptionKey)
  })
_sym_db.RegisterMessage(PublicKeyEncryptionKey)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z+github.com/pomerium/pomerium/pkg/grpc/crypt'
  _SEALEDMESSAGE._serialized_start=37
  _SEALEDMESSAGE._serialized_end=146
  _PUBLICKEYENCRYPTIONKEY._serialized_start=148
  _PUBLICKEYENCRYPTIONKEY._serialized_end=198
# @@protoc_insertion_point(module_scope)
