"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class User(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VERSION_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    GROUP_IDS_FIELD_NUMBER: builtins.int
    DISPLAY_NAME_FIELD_NUMBER: builtins.int
    EMAIL_FIELD_NUMBER: builtins.int
    version: builtins.str
    id: builtins.str
    @property
    def group_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    display_name: builtins.str
    email: builtins.str
    def __init__(
        self,
        *,
        version: builtins.str = ...,
        id: builtins.str = ...,
        group_ids: collections.abc.Iterable[builtins.str] | None = ...,
        display_name: builtins.str = ...,
        email: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["display_name", b"display_name", "email", b"email", "group_ids", b"group_ids", "id", b"id", "version", b"version"]) -> None: ...

global___User = User

class Group(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VERSION_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    EMAIL_FIELD_NUMBER: builtins.int
    version: builtins.str
    id: builtins.str
    name: builtins.str
    email: builtins.str
    def __init__(
        self,
        *,
        version: builtins.str = ...,
        id: builtins.str = ...,
        name: builtins.str = ...,
        email: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["email", b"email", "id", b"id", "name", b"name", "version", b"version"]) -> None: ...

global___Group = Group

class RefreshUserRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    ACCESS_TOKEN_FIELD_NUMBER: builtins.int
    user_id: builtins.str
    access_token: builtins.str
    def __init__(
        self,
        *,
        user_id: builtins.str = ...,
        access_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["access_token", b"access_token", "user_id", b"user_id"]) -> None: ...

global___RefreshUserRequest = RefreshUserRequest
