# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/pomerium/pomerium/pkg/grpc/directory/directory.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?github.com/pomerium/pomerium/pkg/grpc/directory/directory.proto\x12\tdirectory\x1a\x1bgoogle/protobuf/empty.proto\"[\n\x04User\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x11\n\tgroup_ids\x18\x03 \x03(\t\x12\x14\n\x0c\x64isplay_name\x18\x04 \x01(\t\x12\r\n\x05\x65mail\x18\x05 \x01(\t\"A\n\x05Group\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\";\n\x12RefreshUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x02 \x01(\t2X\n\x10\x44irectoryService\x12\x44\n\x0bRefreshUser\x12\x1d.directory.RefreshUserRequest\x1a\x16.google.protobuf.EmptyB1Z/github.com/pomerium/pomerium/pkg/grpc/directoryb\x06proto3')



_USER = DESCRIPTOR.message_types_by_name['User']
_GROUP = DESCRIPTOR.message_types_by_name['Group']
_REFRESHUSERREQUEST = DESCRIPTOR.message_types_by_name['RefreshUserRequest']
User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'github.com.pomerium.pomerium.pkg.grpc.directory.directory_pb2'
  # @@protoc_insertion_point(class_scope:directory.User)
  })
_sym_db.RegisterMessage(User)

Group = _reflection.GeneratedProtocolMessageType('Group', (_message.Message,), {
  'DESCRIPTOR' : _GROUP,
  '__module__' : 'github.com.pomerium.pomerium.pkg.grpc.directory.directory_pb2'
  # @@protoc_insertion_point(class_scope:directory.Group)
  })
_sym_db.RegisterMessage(Group)

RefreshUserRequest = _reflection.GeneratedProtocolMessageType('RefreshUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _REFRESHUSERREQUEST,
  '__module__' : 'github.com.pomerium.pomerium.pkg.grpc.directory.directory_pb2'
  # @@protoc_insertion_point(class_scope:directory.RefreshUserRequest)
  })
_sym_db.RegisterMessage(RefreshUserRequest)

_DIRECTORYSERVICE = DESCRIPTOR.services_by_name['DirectoryService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/github.com/pomerium/pomerium/pkg/grpc/directory'
  _USER._serialized_start=107
  _USER._serialized_end=198
  _GROUP._serialized_start=200
  _GROUP._serialized_end=265
  _REFRESHUSERREQUEST._serialized_start=267
  _REFRESHUSERREQUEST._serialized_end=326
  _DIRECTORYSERVICE._serialized_start=328
  _DIRECTORYSERVICE._serialized_end=416
# @@protoc_insertion_point(module_scope)
