# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/pomerium/pomerium/pkg/grpc/events/idp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6github.com/pomerium/pomerium/pkg/grpc/events/idp.proto\x12\x0fpomerium.events\x1a\x1fgoogle/protobuf/timestamp.proto\"@\n\x0eIDPErrorEvents\x12.\n\x06values\x18\x01 \x03(\x0b\x32\x1e.pomerium.events.IDPErrorEvent\"J\n\rIDPErrorEvent\x12(\n\x04time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07message\x18\x02 \x01(\tB.Z,github.com/pomerium/pomerium/pkg/grpc/eventsb\x06proto3')



_IDPERROREVENTS = DESCRIPTOR.message_types_by_name['IDPErrorEvents']
_IDPERROREVENT = DESCRIPTOR.message_types_by_name['IDPErrorEvent']
IDPErrorEvents = _reflection.GeneratedProtocolMessageType('IDPErrorEvents', (_message.Message,), {
  'DESCRIPTOR' : _IDPERROREVENTS,
  '__module__' : 'github.com.pomerium.pomerium.pkg.grpc.events.idp_pb2'
  # @@protoc_insertion_point(class_scope:pomerium.events.IDPErrorEvents)
  })
_sym_db.RegisterMessage(IDPErrorEvents)

IDPErrorEvent = _reflection.GeneratedProtocolMessageType('IDPErrorEvent', (_message.Message,), {
  'DESCRIPTOR' : _IDPERROREVENT,
  '__module__' : 'github.com.pomerium.pomerium.pkg.grpc.events.idp_pb2'
  # @@protoc_insertion_point(class_scope:pomerium.events.IDPErrorEvent)
  })
_sym_db.RegisterMessage(IDPErrorEvent)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z,github.com/pomerium/pomerium/pkg/grpc/events'
  _IDPERROREVENTS._serialized_start=108
  _IDPERROREVENTS._serialized_end=172
  _IDPERROREVENT._serialized_start=174
  _IDPERROREVENT._serialized_end=248
# @@protoc_insertion_point(module_scope)
