# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/pomerium/pomerium/pkg/grpc/events/last_error.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=github.com/pomerium/pomerium/pkg/grpc/events/last_error.proto\x12\x0fpomerium.events\x1a\x1fgoogle/protobuf/timestamp.proto\"R\n\tLastError\x12(\n\x04time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\tB.Z,github.com/pomerium/pomerium/pkg/grpc/eventsb\x06proto3')



_LASTERROR = DESCRIPTOR.message_types_by_name['LastError']
LastError = _reflection.GeneratedProtocolMessageType('LastError', (_message.Message,), {
  'DESCRIPTOR' : _LASTERROR,
  '__module__' : 'github.com.pomerium.pomerium.pkg.grpc.events.last_error_pb2'
  # @@protoc_insertion_point(class_scope:pomerium.events.LastError)
  })
_sym_db.RegisterMessage(LastError)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z,github.com/pomerium/pomerium/pkg/grpc/events'
  _LASTERROR._serialized_start=115
  _LASTERROR._serialized_end=197
# @@protoc_insertion_point(module_scope)
