"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.any_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class EnvoyConfigurationEvents(google.protobuf.message.Message):
    """EnvoyConfigurationEvents is a list of envoy configuration events."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUES_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___EnvoyConfigurationEvent]: ...
    def __init__(
        self,
        *,
        values: collections.abc.Iterable[global___EnvoyConfigurationEvent] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["values", b"values"]) -> None: ...

global___EnvoyConfigurationEvents = EnvoyConfigurationEvents

class EnvoyConfigurationEvent(google.protobuf.message.Message):
    """EnvoyConfigurationEvent is an envoy configuration event."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _EventKind:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _EventKindEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[EnvoyConfigurationEvent._EventKind.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        EVENT_KIND_UNDEFINED: EnvoyConfigurationEvent._EventKind.ValueType  # 0
        EVENT_DISCOVERY_REQUEST_ACK: EnvoyConfigurationEvent._EventKind.ValueType  # 1
        """envoy_service_discovery_v3.DeltaDiscoveryRequest"""
        EVENT_DISCOVERY_REQUEST_NACK: EnvoyConfigurationEvent._EventKind.ValueType  # 2
        EVENT_DISCOVERY_RESPONSE: EnvoyConfigurationEvent._EventKind.ValueType  # 3
        """envoy_service_discovery_v3.DeltaDiscoveryResponse"""

    class EventKind(_EventKind, metaclass=_EventKindEnumTypeWrapper): ...
    EVENT_KIND_UNDEFINED: EnvoyConfigurationEvent.EventKind.ValueType  # 0
    EVENT_DISCOVERY_REQUEST_ACK: EnvoyConfigurationEvent.EventKind.ValueType  # 1
    """envoy_service_discovery_v3.DeltaDiscoveryRequest"""
    EVENT_DISCOVERY_REQUEST_NACK: EnvoyConfigurationEvent.EventKind.ValueType  # 2
    EVENT_DISCOVERY_RESPONSE: EnvoyConfigurationEvent.EventKind.ValueType  # 3
    """envoy_service_discovery_v3.DeltaDiscoveryResponse"""

    TIME_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    CODE_FIELD_NUMBER: builtins.int
    DETAILS_FIELD_NUMBER: builtins.int
    CONFIG_VERSION_FIELD_NUMBER: builtins.int
    TYPE_URL_FIELD_NUMBER: builtins.int
    KIND_FIELD_NUMBER: builtins.int
    RESOURCE_SUBSCRIBED_FIELD_NUMBER: builtins.int
    RESOURCE_UNSUBSCRIBED_FIELD_NUMBER: builtins.int
    INSTANCE_FIELD_NUMBER: builtins.int
    NONCE_FIELD_NUMBER: builtins.int
    @property
    def time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    message: builtins.str
    code: builtins.int
    @property
    def details(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.any_pb2.Any]: ...
    config_version: builtins.int
    """databroker config version"""
    type_url: builtins.str
    """envoy resource type (i.e. listener, cluster)"""
    kind: global___EnvoyConfigurationEvent.EventKind.ValueType
    @property
    def resource_subscribed(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def resource_unsubscribed(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    instance: builtins.str
    """instance this event originated from"""
    nonce: builtins.str
    def __init__(
        self,
        *,
        time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        message: builtins.str = ...,
        code: builtins.int = ...,
        details: collections.abc.Iterable[google.protobuf.any_pb2.Any] | None = ...,
        config_version: builtins.int = ...,
        type_url: builtins.str = ...,
        kind: global___EnvoyConfigurationEvent.EventKind.ValueType = ...,
        resource_subscribed: collections.abc.Iterable[builtins.str] | None = ...,
        resource_unsubscribed: collections.abc.Iterable[builtins.str] | None = ...,
        instance: builtins.str = ...,
        nonce: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["time", b"time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["code", b"code", "config_version", b"config_version", "details", b"details", "instance", b"instance", "kind", b"kind", "message", b"message", "nonce", b"nonce", "resource_subscribed", b"resource_subscribed", "resource_unsubscribed", b"resource_unsubscribed", "time", b"time", "type_url", b"type_url"]) -> None: ...

global___EnvoyConfigurationEvent = EnvoyConfigurationEvent
