# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/pomerium/pomerium/pkg/grpc/events/xds.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6github.com/pomerium/pomerium/pkg/grpc/events/xds.proto\x12\x0fpomerium.events\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\"T\n\x18\x45nvoyConfigurationEvents\x12\x38\n\x06values\x18\x01 \x03(\x0b\x32(.pomerium.events.EnvoyConfigurationEvent\"\xdb\x03\n\x17\x45nvoyConfigurationEvent\x12(\n\x04time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x63ode\x18\x03 \x01(\x05\x12%\n\x07\x64\x65tails\x18\x04 \x03(\x0b\x32\x14.google.protobuf.Any\x12\x16\n\x0e\x63onfig_version\x18\x05 \x01(\x04\x12\x10\n\x08type_url\x18\x06 \x01(\t\x12@\n\x04kind\x18\x07 \x01(\x0e\x32\x32.pomerium.events.EnvoyConfigurationEvent.EventKind\x12\x1b\n\x13resource_subscribed\x18\x08 \x03(\t\x12\x1d\n\x15resource_unsubscribed\x18\t \x03(\t\x12\x10\n\x08instance\x18\n \x01(\t\x12\r\n\x05nonce\x18\x0b \x01(\t\"\x86\x01\n\tEventKind\x12\x18\n\x14\x45VENT_KIND_UNDEFINED\x10\x00\x12\x1f\n\x1b\x45VENT_DISCOVERY_REQUEST_ACK\x10\x01\x12 \n\x1c\x45VENT_DISCOVERY_REQUEST_NACK\x10\x02\x12\x1c\n\x18\x45VENT_DISCOVERY_RESPONSE\x10\x03\x42.Z,github.com/pomerium/pomerium/pkg/grpc/eventsb\x06proto3')



_ENVOYCONFIGURATIONEVENTS = DESCRIPTOR.message_types_by_name['EnvoyConfigurationEvents']
_ENVOYCONFIGURATIONEVENT = DESCRIPTOR.message_types_by_name['EnvoyConfigurationEvent']
_ENVOYCONFIGURATIONEVENT_EVENTKIND = _ENVOYCONFIGURATIONEVENT.enum_types_by_name['EventKind']
EnvoyConfigurationEvents = _reflection.GeneratedProtocolMessageType('EnvoyConfigurationEvents', (_message.Message,), {
  'DESCRIPTOR' : _ENVOYCONFIGURATIONEVENTS,
  '__module__' : 'github.com.pomerium.pomerium.pkg.grpc.events.xds_pb2'
  # @@protoc_insertion_point(class_scope:pomerium.events.EnvoyConfigurationEvents)
  })
_sym_db.RegisterMessage(EnvoyConfigurationEvents)

EnvoyConfigurationEvent = _reflection.GeneratedProtocolMessageType('EnvoyConfigurationEvent', (_message.Message,), {
  'DESCRIPTOR' : _ENVOYCONFIGURATIONEVENT,
  '__module__' : 'github.com.pomerium.pomerium.pkg.grpc.events.xds_pb2'
  # @@protoc_insertion_point(class_scope:pomerium.events.EnvoyConfigurationEvent)
  })
_sym_db.RegisterMessage(EnvoyConfigurationEvent)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z,github.com/pomerium/pomerium/pkg/grpc/events'
  _ENVOYCONFIGURATIONEVENTS._serialized_start=135
  _ENVOYCONFIGURATIONEVENTS._serialized_end=219
  _ENVOYCONFIGURATIONEVENT._serialized_start=222
  _ENVOYCONFIGURATIONEVENT._serialized_end=697
  _ENVOYCONFIGURATIONEVENT_EVENTKIND._serialized_start=563
  _ENVOYCONFIGURATIONEVENT_EVENTKIND._serialized_end=697
# @@protoc_insertion_point(module_scope)
