"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import envoy.config.core.v3.address_pb2
import envoy.config.core.v3.base_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class AttributeContext(google.protobuf.message.Message):
    """See :ref:`network filter configuration overview <config_network_filters_ext_authz>`
    and :ref:`HTTP filter configuration overview <config_http_filters_ext_authz>`.

    An attribute is a piece of metadata that describes an activity on a network.
    For example, the size of an HTTP request, or the status code of an HTTP response.

    Each attribute has a type and a name, which is logically defined as a proto message field
    of the ``AttributeContext``. The ``AttributeContext`` is a collection of individual attributes
    supported by Envoy authorization system.
    [#comment: The following items are left out of this proto
    Request.Auth field for jwt tokens
    Request.Api for api management
    Origin peer that originated the request
    Caching Protocol
    request_context return values to inject back into the filter chain
    peer.claims -- from X.509 extensions
    Configuration
    - field mask to send
    - which return values from request_context are copied back
    - which return values are copied into request_headers]
    [#next-free-field: 12]
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class Peer(google.protobuf.message.Message):
        """This message defines attributes for a node that handles a network request.
        The node can be either a service or an application that sends, forwards,
        or receives the request. Service peers should fill in the ``service``,
        ``principal``, and ``labels`` as appropriate.
        [#next-free-field: 6]
        """

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        class LabelsEntry(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            KEY_FIELD_NUMBER: builtins.int
            VALUE_FIELD_NUMBER: builtins.int
            key: builtins.str
            value: builtins.str
            def __init__(
                self,
                *,
                key: builtins.str = ...,
                value: builtins.str = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

        ADDRESS_FIELD_NUMBER: builtins.int
        SERVICE_FIELD_NUMBER: builtins.int
        LABELS_FIELD_NUMBER: builtins.int
        PRINCIPAL_FIELD_NUMBER: builtins.int
        CERTIFICATE_FIELD_NUMBER: builtins.int
        @property
        def address(self) -> envoy.config.core.v3.address_pb2.Address:
            """The address of the peer, this is typically the IP address.
            It can also be UDS path, or others.
            """
        service: builtins.str
        """The canonical service name of the peer.
        It should be set to :ref:`the HTTP x-envoy-downstream-service-cluster
        <config_http_conn_man_headers_downstream-service-cluster>`
        If a more trusted source of the service name is available through mTLS/secure naming, it
        should be used.
        """
        @property
        def labels(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
            """The labels associated with the peer.
            These could be pod labels for Kubernetes or tags for VMs.
            The source of the labels could be an X.509 certificate or other configuration.
            """
        principal: builtins.str
        """The authenticated identity of this peer.
        For example, the identity associated with the workload such as a service account.
        If an X.509 certificate is used to assert the identity this field should be sourced from
        ``URI Subject Alternative Names``, ``DNS Subject Alternate Names`` or ``Subject`` in that order.
        The primary identity should be the principal. The principal format is issuer specific.

        Example:
        *    SPIFFE format is ``spiffe://trust-domain/path``
        *    Google account format is ``https://accounts.google.com/{userid}``
        """
        certificate: builtins.str
        """The X.509 certificate used to authenticate the identify of this peer.
        When present, the certificate contents are encoded in URL and PEM format.
        """
        def __init__(
            self,
            *,
            address: envoy.config.core.v3.address_pb2.Address | None = ...,
            service: builtins.str = ...,
            labels: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
            principal: builtins.str = ...,
            certificate: builtins.str = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["address", b"address"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["address", b"address", "certificate", b"certificate", "labels", b"labels", "principal", b"principal", "service", b"service"]) -> None: ...

    class Request(google.protobuf.message.Message):
        """Represents a network request, such as an HTTP request."""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        TIME_FIELD_NUMBER: builtins.int
        HTTP_FIELD_NUMBER: builtins.int
        @property
        def time(self) -> google.protobuf.timestamp_pb2.Timestamp:
            """The timestamp when the proxy receives the first byte of the request."""
        @property
        def http(self) -> global___AttributeContext.HttpRequest:
            """Represents an HTTP request or an HTTP-like request."""
        def __init__(
            self,
            *,
            time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
            http: global___AttributeContext.HttpRequest | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["http", b"http", "time", b"time"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["http", b"http", "time", b"time"]) -> None: ...

    class HttpRequest(google.protobuf.message.Message):
        """This message defines attributes for an HTTP request.
        HTTP/1.x, HTTP/2, gRPC are all considered as HTTP requests.
        [#next-free-field: 13]
        """

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        class HeadersEntry(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            KEY_FIELD_NUMBER: builtins.int
            VALUE_FIELD_NUMBER: builtins.int
            key: builtins.str
            value: builtins.str
            def __init__(
                self,
                *,
                key: builtins.str = ...,
                value: builtins.str = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

        ID_FIELD_NUMBER: builtins.int
        METHOD_FIELD_NUMBER: builtins.int
        HEADERS_FIELD_NUMBER: builtins.int
        PATH_FIELD_NUMBER: builtins.int
        HOST_FIELD_NUMBER: builtins.int
        SCHEME_FIELD_NUMBER: builtins.int
        QUERY_FIELD_NUMBER: builtins.int
        FRAGMENT_FIELD_NUMBER: builtins.int
        SIZE_FIELD_NUMBER: builtins.int
        PROTOCOL_FIELD_NUMBER: builtins.int
        BODY_FIELD_NUMBER: builtins.int
        RAW_BODY_FIELD_NUMBER: builtins.int
        id: builtins.str
        """The unique ID for a request, which can be propagated to downstream
        systems. The ID should have low probability of collision
        within a single day for a specific service.
        For HTTP requests, it should be X-Request-ID or equivalent.
        """
        method: builtins.str
        """The HTTP request method, such as ``GET``, ``POST``."""
        @property
        def headers(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
            """The HTTP request headers. If multiple headers share the same key, they
            must be merged according to the HTTP spec. All header keys must be
            lower-cased, because HTTP header keys are case-insensitive.
            """
        path: builtins.str
        """The request target, as it appears in the first line of the HTTP request. This includes
        the URL path and query-string. No decoding is performed.
        """
        host: builtins.str
        """The HTTP request ``Host`` or '`Authority`` header value."""
        scheme: builtins.str
        """The HTTP URL scheme, such as ``http`` and ``https``."""
        query: builtins.str
        """This field is always empty, and exists for compatibility reasons. The HTTP URL query is
        included in ``path`` field.
        """
        fragment: builtins.str
        """This field is always empty, and exists for compatibility reasons. The URL fragment is
        not submitted as part of HTTP requests; it is unknowable.
        """
        size: builtins.int
        """The HTTP request size in bytes. If unknown, it must be -1."""
        protocol: builtins.str
        """The network protocol used with the request, such as "HTTP/1.0", "HTTP/1.1", or "HTTP/2".

        See :repo:`headers.h:ProtocolStrings <source/common/http/headers.h>` for a list of all
        possible values.
        """
        body: builtins.str
        """The HTTP request body."""
        raw_body: builtins.bytes
        """The HTTP request body in bytes. This is used instead of
        :ref:`body <envoy_v3_api_field_service.auth.v3.AttributeContext.HttpRequest.body>` when
        :ref:`pack_as_bytes <envoy_v3_api_field_extensions.filters.http.ext_authz.v3.BufferSettings.pack_as_bytes>`
        is set to true.
        """
        def __init__(
            self,
            *,
            id: builtins.str = ...,
            method: builtins.str = ...,
            headers: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
            path: builtins.str = ...,
            host: builtins.str = ...,
            scheme: builtins.str = ...,
            query: builtins.str = ...,
            fragment: builtins.str = ...,
            size: builtins.int = ...,
            protocol: builtins.str = ...,
            body: builtins.str = ...,
            raw_body: builtins.bytes = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["body", b"body", "fragment", b"fragment", "headers", b"headers", "host", b"host", "id", b"id", "method", b"method", "path", b"path", "protocol", b"protocol", "query", b"query", "raw_body", b"raw_body", "scheme", b"scheme", "size", b"size"]) -> None: ...

    class ContextExtensionsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    SOURCE_FIELD_NUMBER: builtins.int
    DESTINATION_FIELD_NUMBER: builtins.int
    REQUEST_FIELD_NUMBER: builtins.int
    CONTEXT_EXTENSIONS_FIELD_NUMBER: builtins.int
    METADATA_CONTEXT_FIELD_NUMBER: builtins.int
    @property
    def source(self) -> global___AttributeContext.Peer:
        """The source of a network activity, such as starting a TCP connection.
        In a multi hop network activity, the source represents the sender of the
        last hop.
        """
    @property
    def destination(self) -> global___AttributeContext.Peer:
        """The destination of a network activity, such as accepting a TCP connection.
        In a multi hop network activity, the destination represents the receiver of
        the last hop.
        """
    @property
    def request(self) -> global___AttributeContext.Request:
        """Represents a network request, such as an HTTP request."""
    @property
    def context_extensions(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """This is analogous to http_request.headers, however these contents will not be sent to the
        upstream server. Context_extensions provide an extension mechanism for sending additional
        information to the auth server without modifying the proto definition. It maps to the
        internal opaque context in the filter chain.
        """
    @property
    def metadata_context(self) -> envoy.config.core.v3.base_pb2.Metadata:
        """Dynamic metadata associated with the request."""
    def __init__(
        self,
        *,
        source: global___AttributeContext.Peer | None = ...,
        destination: global___AttributeContext.Peer | None = ...,
        request: global___AttributeContext.Request | None = ...,
        context_extensions: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        metadata_context: envoy.config.core.v3.base_pb2.Metadata | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["destination", b"destination", "metadata_context", b"metadata_context", "request", b"request", "source", b"source"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["context_extensions", b"context_extensions", "destination", b"destination", "metadata_context", b"metadata_context", "request", b"request", "source", b"source"]) -> None: ...

global___AttributeContext = AttributeContext
