#!/bin/bash
set -euo pipefail

_project_root="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)/.."

update-pomerium() {
	pushd "$_project_root"

	git submodule update --remote deps/github.com/pomerium

	popd
}

run() {
	local _command="$1"
	case "$_command" in
	pomerium)
		update-pomerium
		;;
	*)
		echo "unknown command $_command"
		exit 1
		;;
	esac
}

run "${1?'command is required'}"
