# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/pomerium/pomerium/pkg/grpc/registry/registry.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=github.com/pomerium/pomerium/pkg/grpc/registry/registry.proto\x12\x08registry\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x19google/protobuf/any.proto\x1a\x17validate/validate.proto\"T\n\x07Service\x12-\n\x04kind\x18\x01 \x01(\x0e\x32\x15.registry.ServiceKindB\x08\xfa\x42\x05\x82\x01\x02 \x00\x12\x1a\n\x08\x65ndpoint\x18\x03 \x01(\tB\x08\xfa\x42\x05r\x03\x88\x01\x01\"\xc2\x01\n\x0fRegisterRequest\x12-\n\x08services\x18\x01 \x03(\x0b\x32\x11.registry.ServiceB\x08\xfa\x42\x05\x92\x01\x02\x08\x01\x12\x39\n\x08metadata\x18\x02 \x03(\x0b\x32\'.registry.RegisterRequest.MetadataEntry\x1a\x45\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any:\x02\x38\x01\"F\n\x10RegisterResponse\x12\x32\n\x0f\x63\x61ll_back_after\x18\x02 \x01(\x0b\x32\x19.google.protobuf.Duration\"3\n\x0bListRequest\x12$\n\x05kinds\x18\x01 \x03(\x0e\x32\x15.registry.ServiceKind\"i\n\x13ServiceRegistration\x12\"\n\x07service\x18\x01 \x01(\x0b\x32\x11.registry.Service\x12.\n\nexpires_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"2\n\x0bServiceList\x12#\n\x08services\x18\x01 \x03(\x0b\x32\x11.registry.Service*\x96\x01\n\x0bServiceKind\x12\x18\n\x14UNDEFINED_DO_NOT_USE\x10\x00\x12\x0e\n\nDATABROKER\x10\x01\x12\r\n\tAUTHORIZE\x10\x02\x12\x10\n\x0c\x41UTHENTICATE\x10\x03\x12\t\n\x05PROXY\x10\x04\x12\x0c\n\x08REGISTRY\x10\x05\x12\x0b\n\x07\x43ONSOLE\x10\x06\x12\x16\n\x12PROMETHEUS_METRICS\x10\x07\x32\xba\x01\n\x08Registry\x12?\n\x06Report\x12\x19.registry.RegisterRequest\x1a\x1a.registry.RegisterResponse\x12\x34\n\x04List\x12\x15.registry.ListRequest\x1a\x15.registry.ServiceList\x12\x37\n\x05Watch\x12\x15.registry.ListRequest\x1a\x15.registry.ServiceList0\x01\x42\x30Z.github.com/pomerium/pomerium/pkg/grpc/registryb\x06proto3')

_SERVICEKIND = DESCRIPTOR.enum_types_by_name['ServiceKind']
ServiceKind = enum_type_wrapper.EnumTypeWrapper(_SERVICEKIND)
UNDEFINED_DO_NOT_USE = 0
DATABROKER = 1
AUTHORIZE = 2
AUTHENTICATE = 3
PROXY = 4
REGISTRY = 5
CONSOLE = 6
PROMETHEUS_METRICS = 7


_SERVICE = DESCRIPTOR.message_types_by_name['Service']
_REGISTERREQUEST = DESCRIPTOR.message_types_by_name['RegisterRequest']
_REGISTERREQUEST_METADATAENTRY = _REGISTERREQUEST.nested_types_by_name['MetadataEntry']
_REGISTERRESPONSE = DESCRIPTOR.message_types_by_name['RegisterResponse']
_LISTREQUEST = DESCRIPTOR.message_types_by_name['ListRequest']
_SERVICEREGISTRATION = DESCRIPTOR.message_types_by_name['ServiceRegistration']
_SERVICELIST = DESCRIPTOR.message_types_by_name['ServiceList']
Service = _reflection.GeneratedProtocolMessageType('Service', (_message.Message,), {
  'DESCRIPTOR' : _SERVICE,
  '__module__' : 'github.com.pomerium.pomerium.pkg.grpc.registry.registry_pb2'
  # @@protoc_insertion_point(class_scope:registry.Service)
  })
_sym_db.RegisterMessage(Service)

RegisterRequest = _reflection.GeneratedProtocolMessageType('RegisterRequest', (_message.Message,), {

  'MetadataEntry' : _reflection.GeneratedProtocolMessageType('MetadataEntry', (_message.Message,), {
    'DESCRIPTOR' : _REGISTERREQUEST_METADATAENTRY,
    '__module__' : 'github.com.pomerium.pomerium.pkg.grpc.registry.registry_pb2'
    # @@protoc_insertion_point(class_scope:registry.RegisterRequest.MetadataEntry)
    })
  ,
  'DESCRIPTOR' : _REGISTERREQUEST,
  '__module__' : 'github.com.pomerium.pomerium.pkg.grpc.registry.registry_pb2'
  # @@protoc_insertion_point(class_scope:registry.RegisterRequest)
  })
_sym_db.RegisterMessage(RegisterRequest)
_sym_db.RegisterMessage(RegisterRequest.MetadataEntry)

RegisterResponse = _reflection.GeneratedProtocolMessageType('RegisterResponse', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERRESPONSE,
  '__module__' : 'github.com.pomerium.pomerium.pkg.grpc.registry.registry_pb2'
  # @@protoc_insertion_point(class_scope:registry.RegisterResponse)
  })
_sym_db.RegisterMessage(RegisterResponse)

ListRequest = _reflection.GeneratedProtocolMessageType('ListRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTREQUEST,
  '__module__' : 'github.com.pomerium.pomerium.pkg.grpc.registry.registry_pb2'
  # @@protoc_insertion_point(class_scope:registry.ListRequest)
  })
_sym_db.RegisterMessage(ListRequest)

ServiceRegistration = _reflection.GeneratedProtocolMessageType('ServiceRegistration', (_message.Message,), {
  'DESCRIPTOR' : _SERVICEREGISTRATION,
  '__module__' : 'github.com.pomerium.pomerium.pkg.grpc.registry.registry_pb2'
  # @@protoc_insertion_point(class_scope:registry.ServiceRegistration)
  })
_sym_db.RegisterMessage(ServiceRegistration)

ServiceList = _reflection.GeneratedProtocolMessageType('ServiceList', (_message.Message,), {
  'DESCRIPTOR' : _SERVICELIST,
  '__module__' : 'github.com.pomerium.pomerium.pkg.grpc.registry.registry_pb2'
  # @@protoc_insertion_point(class_scope:registry.ServiceList)
  })
_sym_db.RegisterMessage(ServiceList)

_REGISTRY = DESCRIPTOR.services_by_name['Registry']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z.github.com/pomerium/pomerium/pkg/grpc/registry'
  _SERVICE.fields_by_name['kind']._options = None
  _SERVICE.fields_by_name['kind']._serialized_options = b'\372B\005\202\001\002 \000'
  _SERVICE.fields_by_name['endpoint']._options = None
  _SERVICE.fields_by_name['endpoint']._serialized_options = b'\372B\005r\003\210\001\001'
  _REGISTERREQUEST_METADATAENTRY._options = None
  _REGISTERREQUEST_METADATAENTRY._serialized_options = b'8\001'
  _REGISTERREQUEST.fields_by_name['services']._options = None
  _REGISTERREQUEST.fields_by_name['services']._serialized_options = b'\372B\005\222\001\002\010\001'
  _SERVICEKIND._serialized_start=760
  _SERVICEKIND._serialized_end=910
  _SERVICE._serialized_start=192
  _SERVICE._serialized_end=276
  _REGISTERREQUEST._serialized_start=279
  _REGISTERREQUEST._serialized_end=473
  _REGISTERREQUEST_METADATAENTRY._serialized_start=404
  _REGISTERREQUEST_METADATAENTRY._serialized_end=473
  _REGISTERRESPONSE._serialized_start=475
  _REGISTERRESPONSE._serialized_end=545
  _LISTREQUEST._serialized_start=547
  _LISTREQUEST._serialized_end=598
  _SERVICEREGISTRATION._serialized_start=600
  _SERVICEREGISTRATION._serialized_end=705
  _SERVICELIST._serialized_start=707
  _SERVICELIST._serialized_end=757
  _REGISTRY._serialized_start=913
  _REGISTRY._serialized_end=1099
# @@protoc_insertion_point(module_scope)
