"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.any_pb2
import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _ServiceKind:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ServiceKindEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ServiceKind.ValueType], builtins.type):  # noqa: F821
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UNDEFINED_DO_NOT_USE: _ServiceKind.ValueType  # 0
    DATABROKER: _ServiceKind.ValueType  # 1
    """databroker grpc service"""
    AUTHORIZE: _ServiceKind.ValueType  # 2
    """authorize grpc service"""
    AUTHENTICATE: _ServiceKind.ValueType  # 3
    """authentication http(s) service"""
    PROXY: _ServiceKind.ValueType  # 4
    """proxy service"""
    REGISTRY: _ServiceKind.ValueType  # 5
    """registry service"""
    CONSOLE: _ServiceKind.ValueType  # 6
    """console grpc service"""
    PROMETHEUS_METRICS: _ServiceKind.ValueType  # 7
    """prometheus metrics compatible http endpoint"""

class ServiceKind(_ServiceKind, metaclass=_ServiceKindEnumTypeWrapper): ...

UNDEFINED_DO_NOT_USE: ServiceKind.ValueType  # 0
DATABROKER: ServiceKind.ValueType  # 1
"""databroker grpc service"""
AUTHORIZE: ServiceKind.ValueType  # 2
"""authorize grpc service"""
AUTHENTICATE: ServiceKind.ValueType  # 3
"""authentication http(s) service"""
PROXY: ServiceKind.ValueType  # 4
"""proxy service"""
REGISTRY: ServiceKind.ValueType  # 5
"""registry service"""
CONSOLE: ServiceKind.ValueType  # 6
"""console grpc service"""
PROMETHEUS_METRICS: ServiceKind.ValueType  # 7
"""prometheus metrics compatible http endpoint"""
global___ServiceKind = ServiceKind

class Service(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KIND_FIELD_NUMBER: builtins.int
    ENDPOINT_FIELD_NUMBER: builtins.int
    kind: global___ServiceKind.ValueType
    """kind is service kind"""
    endpoint: builtins.str
    """network endpoints this service may be reachable at"""
    def __init__(
        self,
        *,
        kind: global___ServiceKind.ValueType = ...,
        endpoint: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["endpoint", b"endpoint", "kind", b"kind"]) -> None: ...

global___Service = Service

class RegisterRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class MetadataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> google.protobuf.any_pb2.Any: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: google.protobuf.any_pb2.Any | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    SERVICES_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    @property
    def services(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Service]:
        """services this deployment runs"""
    @property
    def metadata(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, google.protobuf.any_pb2.Any]:
        """service may optionally provide certain metadata, such as
        - build version
        - startup time
        - bootstrap configuration
        - OS, OS version, OS hostname
        - etc
        this information is not distributed back to the inquiring nodes
        and may also have a different storage and time to live
        """
    def __init__(
        self,
        *,
        services: collections.abc.Iterable[global___Service] | None = ...,
        metadata: collections.abc.Mapping[builtins.str, google.protobuf.any_pb2.Any] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["metadata", b"metadata", "services", b"services"]) -> None: ...

global___RegisterRequest = RegisterRequest

class RegisterResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CALL_BACK_AFTER_FIELD_NUMBER: builtins.int
    @property
    def call_back_after(self) -> google.protobuf.duration_pb2.Duration:
        """indicates when to report back again"""
    def __init__(
        self,
        *,
        call_back_after: google.protobuf.duration_pb2.Duration | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["call_back_after", b"call_back_after"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["call_back_after", b"call_back_after"]) -> None: ...

global___RegisterResponse = RegisterResponse

class ListRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KINDS_FIELD_NUMBER: builtins.int
    @property
    def kinds(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___ServiceKind.ValueType]: ...
    def __init__(
        self,
        *,
        kinds: collections.abc.Iterable[global___ServiceKind.ValueType] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["kinds", b"kinds"]) -> None: ...

global___ListRequest = ListRequest

class ServiceRegistration(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERVICE_FIELD_NUMBER: builtins.int
    EXPIRES_AT_FIELD_NUMBER: builtins.int
    @property
    def service(self) -> global___Service: ...
    @property
    def expires_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        service: global___Service | None = ...,
        expires_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["expires_at", b"expires_at", "service", b"service"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["expires_at", b"expires_at", "service", b"service"]) -> None: ...

global___ServiceRegistration = ServiceRegistration

class ServiceList(google.protobuf.message.Message):
    """RegistrationSnapshot represents the current state of the services"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERVICES_FIELD_NUMBER: builtins.int
    @property
    def services(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Service]: ...
    def __init__(
        self,
        *,
        services: collections.abc.Iterable[global___Service] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["services", b"services"]) -> None: ...

global___ServiceList = ServiceList
