name: Update

on:
  pull_request:

jobs:
  update-pomerium-core:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          ref: ${{ github.head_ref }}

      - run: |
        ./scripts/update
