name: Update

on:
  pull_request:

jobs:
  update-pomerium-core:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          ref: ${{ github.head_ref }}
          submodules: "true"
          token: ${{ secrets.APPARITOR_GITHUB_TOKEN }}

      - name: Update
        run: |
          ./scripts/update

      - name: Check for changes
        id: git-diff
        run: |
          git config --global user.email "apparitor@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git diff --cached --exit-code || echo "changed=true" >> $GITHUB_OUTPUT
          git commit -m "regenerate"
          git push

      - name: Commit
        if: ${{ steps.git-diff.outputs.changed }} == 'true'
        run: |
          echo "COMMIT"
